name: Orchestrator Backend Update

on:
  repository_dispatch:
    types: [microservice-updated]

jobs:
  update-backend-image:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout orchestrator repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2️⃣ Set backend image metadata from dispatch payload
      - name: Set backend image metadata
        run: |
          echo "BACKEND_IMAGE=${{ github.event.client_payload.image }}" >> $GITHUB_ENV
          echo "IMAGE_NAME=$(echo $BACKEND_IMAGE | cut -d':' -f1)" >> $GITHUB_ENV
          echo "IMAGE_TAG=$(echo $BACKEND_IMAGE | cut -d':' -f2)" >> $GITHUB_ENV

      # 3️⃣ Display debug info
      - name: Show backend image info
        run: |
          echo "Full image: $BACKEND_IMAGE"
          echo "Image name: $IMAGE_NAME"
          echo "Image tag: $IMAGE_TAG"

      # 4️⃣ Update docker-compose.override.yml
      - name: Override backend image in Compose file
        run: |
          COMPOSE_FILE=docker-compose.test.yml
          # Backup original file
          cp $COMPOSE_FILE $COMPOSE_FILE.bak
          # Replace image line
          sed -i "s|image: $IMAGE_NAME:latest|image: $BACKEND_IMAGE|g" $COMPOSE_FILE

      # 5️⃣ Pull and start updated stack
      # - name: Pull & start stack
      #   run: |
      #     docker-compose pull
      #     docker-compose up -d

      # 6️⃣ Optional: Run E2E / integration tests
      # - name: Run tests
      #   run: |
      #     pytest tests/e2e/
